### ISSUE TITLE
Firefox: problem with "getPaperSize()"

### ISSUE THREAD

**Issue by blucobalto** [oslego/Snap.FreeTransform#1]
Hi Oslego,
thank you for sharing your work. 

I found a problem with "getPaperSize()". Does not work with Firefox (ver 32.0 / 33.0).

I modified the following code: 
getPaperSize function () {
    return {
        x: parseInt(paper.node.clientWidth),
        y: parseInt(paper.node.clientHeight)
    }
}

with: 

getPaperSize function () {
    return {
         x: paper.node.clientWidth || paper.node.parentElement.clientWidth,
         y: paper.node.clientHeight || paper.node.parentElement.clientHeight
    }
}

The changes "seem" to work with (IE11 / 33 Firefox / Chrome 38).
You can check it right?

Thanks a lot,
blu

**Comment by oslego** [comment]
Agreed, there seems to be a bug with `.clientWidth` / `.clientHeight` of SVG on Firefox. According to [this comment](http://stackoverflow.com/a/13123366/78601), there's a fix coming up.

Your solution might work, but it is dependent on context. It gets the size of to the parent node of the SVG node which may, or may not be the same size as the SVG itself.

I'll make a note to revisit this to check if Firefox has fixed the bug.
