### ISSUE TITLE
Change the position of rotate cercle

### ISSUE THREAD

**Issue by ktarak** [oslego/Snap.FreeTransform#3]
Hello, Great work and it's very helpful.

I work in simulator website and when i add Snap free Transform Plugin to transform an object, everythings work good but when we use the rotate's position, it's shown in bottom of object but i want it in top. we changed the "distance" variable value to negatif and it doesn't work to.
PLease help.
In advance thanks

**Comment by oslego** [comment]
@ktarak I'm not aware of a setting for the position of the controls.

Snap.FreeTransform is just an adaptation of [Raphael.FreeTransform](https://github.com/AliasIO/Raphael.FreeTransform). Perhaps you can find an answer to your question there. 

This is a UI with all the configurable settings:
https://alias.io/raphael/free_transform/

**Update**: You'll probably have to make a fork and change things yourself. Have a look at:
https://github.com/oslego/Snap.FreeTransform/blob/master/snap.freetransform.js#L286
