### ISSUE TITLE
Compatibility with zpd

### ISSUE THREAD

**Issue by astromediaonly** [oslego/Snap.FreeTransform#4]
Hi, 
im not so fammiliar with github so sorry if it does not belongs here. Im trying to figure out how to use this great snap plugin with another one called zpd (https://github.com/huei90/snap.svg.zpd). I was trying to implement it to my existing project so im not entirely sure there is no mistake somewhere else but transform guidelines are misplaced (and while i panning they dont moving with object) and draging interfering with panning of zpd it self ... i can somehow fix that dragging if you could provide me info how i can bind my piece of code to dragstart and dragend handlers of free transform but that i have no idea what to do with that misplaced guidelines. I'll really appreciate if you could help me with that. Thx

PS: Sorry for my english - im not from english speaking country

**Comment by oslego** [comment]
I'm afraid I can't help you with this. I only did a port of the code from Raphael to Snap with minimal updates. I'm not intimately familiar with the code and interactions. 

Your best bet is to dive into the code and debug. Perhaps you can get a clue by searching for similar problems with the plugin's [version for Raphael](https://github.com/AliasIO/Raphael.FreeTransform) (the original source for this plugin).

**Comment by astromediaonly** [comment]
Oh, i see ... i was affraid so ... im not that type feeling comfortable editing someone's else code, maybe i will write something more simple on my own ... thx anyway :)

**Comment by oslego** [comment]
Sounds like zpd gives you most of the same functionality, so augmenting that might be a good option. Or, adding zoom to Snap.FreeTransform, if that's what you need.

Best of luck!
